from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Protocol

from openai import OpenAI

from flybot_core.config import BrainConfig, EnvironmentSettings
from flybot_core.ids import new_identifier
from flybot_core.models import (
    MissionPlan,
    OnFailurePolicy,
    PlanAction,
    PlanStep,
    TargetSpec,
    WorldState,
)


class CognitiveProvider(Protocol):
    async def build_plan(self, instruction: str, world_state: WorldState) -> MissionPlan: ...


@dataclass
class FakeBrainProvider:
    brain_config: BrainConfig

    async def build_plan(self, instruction: str, world_state: WorldState) -> MissionPlan:
        mission_identifier = new_identifier("mission")
        normalized_instruction = instruction.strip().lower()
        if "stop" in normalized_instruction:
            return MissionPlan(
                mission_id=mission_identifier,
                objective=instruction,
                assumptions=["Generated by FakeBrainProvider"],
                steps=[
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=PlanAction.STOP,
                        target=None,
                        parameters={},
                        timeout_s=2.0,
                        on_failure=OnFailurePolicy.STOP,
                    )
                ],
                completion_summary_fields=["status"],
            )

        if "patrol" in normalized_instruction:
            return MissionPlan(
                mission_id=mission_identifier,
                objective=instruction,
                assumptions=["Generated by FakeBrainProvider for PATROL/OBSERVE demo behavior"],
                steps=[
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=PlanAction.PATROL,
                        target=None,
                        parameters={
                            "waypoints": [[0.8, 0.0], [0.8, 0.8], [0.0, 0.8], [0.0, 0.0]],
                            "stand_off_body_lengths": 0.35,
                            "speed": 0.6,
                        },
                        timeout_s=14.0,
                        on_failure=OnFailurePolicy.REPLAN,
                    ),
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=PlanAction.OBSERVE,
                        target=None,
                        parameters={"dwell_s": 3.0, "allow_recording": False},
                        timeout_s=8.0,
                        on_failure=OnFailurePolicy.REPLAN,
                    ),
                ],
                completion_summary_fields=["change_events_count", "recording_enabled"],
            )

        if "follow" in normalized_instruction:
            follow_target = self._resolve_target_spec("green target", world_state)
            return MissionPlan(
                mission_id=mission_identifier,
                objective=instruction,
                assumptions=["Generated by FakeBrainProvider for FOLLOW demo behavior"],
                steps=[
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=PlanAction.FOLLOW,
                        target=follow_target,
                        parameters={
                            "speed": 0.45,
                            "duration_s": 8.0,
                            "min_distance_body_lengths": 1.35,
                            "max_distance_body_lengths": 1.8,
                        },
                        timeout_s=12.0,
                        on_failure=OnFailurePolicy.REPLAN,
                    )
                ],
                completion_summary_fields=["follow_min_distance_observed"],
            )

        if "touch" in normalized_instruction or "nudge" in normalized_instruction:
            touch_target = self._resolve_target_spec(normalized_instruction, world_state)
            touch_action = (
                PlanAction.NUDGE if "nudge" in normalized_instruction else PlanAction.TOUCH
            )
            return MissionPlan(
                mission_id=mission_identifier,
                objective=instruction,
                assumptions=["Generated by FakeBrainProvider for TOUCH/NUDGE demo behavior"],
                steps=[
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=touch_action,
                        target=touch_target,
                        parameters={
                            "speed": 0.45,
                            "stand_off_body_lengths": 0.25,
                            "max_force": 0.35,
                            "retract_distance": 0.8,
                            "nudged_displacement": 0.3,
                        },
                        timeout_s=16.0,
                        on_failure=OnFailurePolicy.STOP,
                    )
                ],
                completion_summary_fields=["touch_contact_count", "touch_target_object_id"],
            )

        if "inspect" in normalized_instruction:
            inspect_target = self._resolve_target_spec(normalized_instruction, world_state)
            return MissionPlan(
                mission_id=mission_identifier,
                objective=instruction,
                assumptions=[
                    "Generated by FakeBrainProvider for INSPECT/RETURN_HOME demo behavior"
                ],
                steps=[
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=PlanAction.INSPECT,
                        target=inspect_target,
                        parameters={
                            "viewpoints": 2,
                            "radius_body_lengths": 0.6,
                            "speed": 0.6,
                            "stand_off_body_lengths": 0.35,
                        },
                        timeout_s=24.0,
                        on_failure=OnFailurePolicy.REPLAN,
                    ),
                    PlanStep(
                        step_id=new_identifier("step"),
                        action=PlanAction.RETURN_HOME,
                        target=None,
                        parameters={"speed": 0.5, "stand_off_body_lengths": 0.7},
                        timeout_s=14.0,
                        on_failure=OnFailurePolicy.STOP,
                    ),
                ],
                completion_summary_fields=["result"],
            )

        resolved_target = self._resolve_target_spec(normalized_instruction, world_state)
        return MissionPlan(
            mission_id=mission_identifier,
            objective=instruction,
            assumptions=["Generated by FakeBrainProvider with deterministic parsing"],
            steps=[
                PlanStep(
                    step_id=new_identifier("step"),
                    action=PlanAction.NAVIGATE,
                    target=resolved_target,
                    parameters={"stand_off_body_lengths": 0.8, "speed": 0.5},
                    timeout_s=30.0,
                    on_failure=OnFailurePolicy.REPLAN,
                )
            ],
            completion_summary_fields=["target", "result"],
        )

    def _resolve_target_spec(self, instruction: str, world_state: WorldState) -> TargetSpec:
        color_pattern = r"(red|blue|green|yellow|white|gray)"
        shape_pattern = r"(cube|block|target|sphere|marker|object)"
        color_match = re.search(color_pattern, instruction)
        shape_match = re.search(shape_pattern, instruction)
        attributes: dict[str, str] = {}
        label: str | None = None
        if color_match is not None:
            attributes["color"] = color_match.group(1)
        if shape_match is not None:
            label = shape_match.group(1)

        for track in world_state.objects:
            if label is not None and track.label != label:
                continue
            if any(track.attributes.get(key) != value for key, value in attributes.items()):
                continue
            return TargetSpec(
                label=track.label, attributes=track.attributes, track_id=track.track_id
            )

        return TargetSpec(label=label or "target", attributes=attributes)


@dataclass
class OpenAICognitiveProvider:
    brain_config: BrainConfig
    openai_model: str
    openai_api_key: str

    async def build_plan(self, instruction: str, world_state: WorldState) -> MissionPlan:
        client = OpenAI(api_key=self.openai_api_key)
        response = client.responses.create(
            model=self.openai_model,
            input=[
                {
                    "role": "system",
                    "content": (
                        "You are FlyBot CognitiveBrain. "
                        "Output only JSON matching MissionPlan fields: "
                        "mission_id, objective, assumptions, steps, completion_summary_fields. "
                        "Actions must be limited to NAVIGATE, SEARCH, PATROL, OBSERVE, "
                        "INSPECT, APPROACH, "
                        "FOLLOW, TOUCH, NUDGE, RETREAT, RETURN_HOME, WAIT, STOP. "
                        "Never emit motor/joint commands."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps(
                        {
                            "instruction": instruction,
                            "world_state": world_state.model_dump(mode="json"),
                            "intent_ttl_ms": 1500,
                        }
                    ),
                },
            ],
            timeout=self.brain_config.request_timeout_s,
        )
        text_output = response.output_text
        return MissionPlan.model_validate_json(text_output)


def create_cognitive_provider(brain_config: BrainConfig) -> CognitiveProvider:
    environment_settings = EnvironmentSettings()
    if brain_config.provider.lower() == "openai":
        if environment_settings.openai_api_key is None:
            raise RuntimeError("OPENAI_API_KEY is required when BRAIN_PROVIDER=openai")
        return OpenAICognitiveProvider(
            brain_config=brain_config,
            openai_model=brain_config.model,
            openai_api_key=environment_settings.openai_api_key,
        )
    return FakeBrainProvider(brain_config=brain_config)
